// Generated by miner/scripts/package.mjs. Do not edit by hand.
import type { MinerReleaseManifest } from "./release";

export const GENERATED_MINER_RELEASE: MinerReleaseManifest = {
  "product": "USAGE Miner",
  "version": "0.3.0",
  "channel": "beta",
  "platform": "win32-x64",
  "builtAt": "2026-09-08T17:52:00.010Z",
  "nodeVersion": "v24.13.1",
  "signed": false,
  "signingNote": "Not code-signed. Windows SmartScreen will warn about an unrecognised publisher. Verify the SHA-256 below before running.",
  "files": [
    {
      "name": "USAGE-Miner-0.3.0.exe",
      "bytes": 91590144,
      "sha256": "a4d2e221135f5e8d25a9acf8cb3ca2e3079afb6f851498ce49e61023da9377b4",
      "reproducible": true
    },
    {
      "name": "USAGE-Miner-0.3.0-Setup.exe",
      "bytes": 91600896,
      "sha256": "770ede5eb302afd7071f538dd6cd51c89d0d7e76af0418286c54fb440fd555b6",
      "reproducible": false
    }
  ]
};
