import { GENERATED_MINER_RELEASE } from "./release.generated";

/**
 * The miner build this server currently offers.
 *
 * Kept beside the server so the download page, the config endpoint and the
 * device list cannot disagree about which version is current.
 *
 * The manifest itself is GENERATED by `miner/scripts/package.mjs` at build
 * time, not written here. A download page that states a checksum a human typed
 * is worse than one with no checksum: it teaches people that a mismatch is
 * probably a typo. The only checksum we publish is the one the build computed
 * over the bytes it produced.
 */

export interface MinerReleaseFile {
  name: string;
  bytes: number;
  /** Lowercase hex, over the exact bytes of the published artifact. */
  sha256: string;
  /** Whether rebuilding from the same source yields these exact bytes. */
  reproducible: boolean;
}

export interface MinerReleaseManifest {
  product: string;
  version: string;
  channel: string;
  platform: string;
  builtAt: string;
  /** The Node runtime embedded in the artifact; a hash means little without it. */
  nodeVersion: string;
  signed: boolean;
  signingNote: string;
  files: MinerReleaseFile[];
}

export const MINER_RELEASE = GENERATED_MINER_RELEASE;
export const MINER_VERSION = MINER_RELEASE.version;
export const MINER_PROTOCOL_VERSION = "miner-protocol-v1";
/** Older builds still work; below this the server may refuse in future. */
export const MINIMUM_MINER_VERSION = "0.1.0";

/**
 * The git tag these artifacts were published under.
 *
 * Set by hand when a release is cut, because the iteration suffix is a human
 * decision that no version string implies: 0.2.0 can be published more than
 * once as beta.1, beta.2, and the binaries differ each time. A test asserts it
 * still contains the manifest's version, so the two cannot drift.
 */
export const MINER_RELEASE_TAG = "v0.2.0-beta.1";

/**
 * Where the artifacts live.
 *
 * Not in this repository and not on this deployment: an 87 MB executable does
 * not belong in a git history or a serverless bundle. It is published as a
 * release asset, and the base is configurable so a fork or a staging build can
 * point somewhere else without editing code.
 */
const REPOSITORY = "https://github.com/Deniscoke/USAGE";

export function downloadUrl(file: MinerReleaseFile): string {
  const base = process.env.USAGE_MINER_DOWNLOAD_BASE;
  if (base) return new URL(file.name, base.endsWith("/") ? base : `${base}/`).toString();
  return `${REPOSITORY}/releases/download/${MINER_RELEASE_TAG}/${file.name}`;
}

/** The release page itself, for anyone who wants the notes and every asset. */
export function releaseUrl(): string {
  return `${REPOSITORY}/releases/tag/${MINER_RELEASE_TAG}`;
}

/** The installer if there is one, else the bare executable. */
export function primaryDownload(): MinerReleaseFile | null {
  return (
    MINER_RELEASE.files.find((file) => file.name.toLowerCase().includes("setup")) ??
    MINER_RELEASE.files[0] ??
    null
  );
}

export function formatBytes(bytes: number): string {
  return `${(bytes / 1024 / 1024).toFixed(0)} MB`;
}
