// Generated by miner/scripts/package.mjs. Do not edit by hand.
import type { MinerReleaseManifest } from "./release";

export const GENERATED_MINER_RELEASE: MinerReleaseManifest = {
  "product": "USAGE Miner",
  "version": "0.2.0",
  "channel": "beta",
  "platform": "win32-x64",
  "builtAt": "2026-09-08T15:34:40.022Z",
  "nodeVersion": "v24.13.1",
  "signed": false,
  "signingNote": "Not code-signed. Windows SmartScreen will warn about an unrecognised publisher. Verify the SHA-256 below before running.",
  "files": [
    {
      "name": "USAGE-Miner-0.2.0.exe",
      "bytes": 91583488,
      "sha256": "9ed4707e761267b7d09f22eeacad252fa7427984e40ba8821ba8edf8821c994e",
      "reproducible": true
    },
    {
      "name": "USAGE-Miner-0.2.0-Setup.exe",
      "bytes": 91593728,
      "sha256": "4fe610e3ea16280b78a8cd84fdbe4e750698128a9bcb2ac2b9e1cd558c74ab04",
      "reproducible": false
    }
  ]
};
